import { ASSET_CATALOG } from "@/lib/assets/asset-catalog";
import type { ScrapbookTemplate } from "@/types/template";

function assetSrc(name: string): string {
  const found = ASSET_CATALOG.find((a) => a.name === name);
  if (!found) throw new Error(`Unknown template asset: ${name}`);
  return found.src;
}

export const TEMPLATE_CATALOG: ScrapbookTemplate[] = [
  {
    id: "birthday-bash",
    name: "Birthday Bash",
    description: "A festive square page for birthday photos and memories.",
    category: "Celebration",
    frame: { width: 1080, height: 1080 },
    swatch: "from-fuchsia-400/40 to-orange-300/30",
    objects: [
      {
        type: "text",
        name: "Title",
        x: 140,
        y: 70,
        width: 800,
        height: 140,
        text: { content: "Happy Birthday!", fontSize: 72, fontWeight: 800 },
      },
      {
        type: "text",
        name: "Subtitle",
        x: 190,
        y: 210,
        width: 700,
        height: 60,
        text: {
          content: "Another year of amazing memories",
          fontSize: 26,
          fontWeight: 500,
        },
      },
      {
        type: "image",
        name: "Photo frame",
        x: 340,
        y: 300,
        width: 400,
        height: 460,
        rotation: -4,
        src: assetSrc("Polaroid"),
      },
      {
        type: "image",
        name: "Washi tape",
        x: 40,
        y: 20,
        width: 220,
        height: 60,
        rotation: -20,
        src: assetSrc("Pink stripes"),
      },
      {
        type: "image",
        name: "Washi tape",
        x: 800,
        y: 40,
        width: 220,
        height: 60,
        rotation: 15,
        src: assetSrc("Blue dots"),
      },
      {
        type: "image",
        name: "Balloon",
        x: 70,
        y: 800,
        width: 130,
        height: 130,
        src: assetSrc("Balloon"),
      },
      {
        type: "image",
        name: "Party",
        x: 880,
        y: 810,
        width: 120,
        height: 120,
        src: assetSrc("Party"),
      },
      {
        type: "image",
        name: "Star",
        x: 900,
        y: 130,
        width: 90,
        height: 90,
        rotation: 12,
        src: assetSrc("Star (pink)"),
      },
      {
        type: "image",
        name: "Sparkles",
        x: 60,
        y: 500,
        width: 90,
        height: 90,
        src: assetSrc("Sparkles"),
      },
    ],
  },
  {
    id: "travel-diary",
    name: "Travel Diary",
    description: "A landscape spread for road trips and adventures.",
    category: "Travel",
    frame: { width: 1920, height: 1080 },
    swatch: "from-sky-300/40 to-violet-300/30",
    objects: [
      {
        type: "text",
        name: "Title",
        x: 100,
        y: 70,
        width: 500,
        height: 100,
        text: { content: "Our Trip", fontSize: 64, fontWeight: 800, align: "left" },
      },
      {
        type: "text",
        name: "Subtitle",
        x: 100,
        y: 180,
        width: 500,
        height: 50,
        text: {
          content: "Adventures worth remembering",
          fontSize: 24,
          fontWeight: 500,
          align: "left",
        },
      },
      {
        type: "image",
        name: "Photo 1",
        x: 650,
        y: 90,
        width: 380,
        height: 440,
        rotation: -6,
        src: assetSrc("Polaroid tilted"),
      },
      {
        type: "image",
        name: "Photo 2",
        x: 1080,
        y: 170,
        width: 380,
        height: 440,
        rotation: 5,
        src: assetSrc("Polaroid tilted right"),
      },
      {
        type: "image",
        name: "Photo 3",
        x: 1500,
        y: 110,
        width: 340,
        height: 400,
        rotation: -3,
        src: assetSrc("Polaroid"),
      },
      {
        type: "image",
        name: "Arrow",
        x: 540,
        y: 560,
        width: 140,
        height: 140,
        rotation: 20,
        src: assetSrc("Arrow"),
      },
      {
        type: "image",
        name: "Camera",
        x: 100,
        y: 820,
        width: 100,
        height: 100,
        src: assetSrc("Camera"),
      },
    ],
  },
  {
    id: "babys-first-year",
    name: "Baby's First Year",
    description: "A soft, gentle portrait layout for baby milestones.",
    category: "Family",
    frame: { width: 1080, height: 1920 },
    swatch: "from-rose-200/40 to-amber-100/30",
    objects: [
      {
        type: "text",
        name: "Title",
        x: 100,
        y: 90,
        width: 880,
        height: 120,
        text: { content: "Baby's First Year", fontSize: 54, fontWeight: 800 },
      },
      {
        type: "image",
        name: "Flower",
        x: 30,
        y: 30,
        width: 160,
        height: 160,
        src: assetSrc("Flower"),
      },
      {
        type: "image",
        name: "Flower",
        x: 870,
        y: 1720,
        width: 160,
        height: 160,
        src: assetSrc("Flower (yellow)"),
      },
      {
        type: "image",
        name: "Leaf",
        x: 850,
        y: 50,
        width: 140,
        height: 140,
        rotation: 25,
        src: assetSrc("Leaf"),
      },
      {
        type: "image",
        name: "Photo frame",
        x: 240,
        y: 300,
        width: 600,
        height: 680,
        src: assetSrc("Polaroid"),
      },
      {
        type: "image",
        name: "Heart",
        x: 100,
        y: 1080,
        width: 90,
        height: 90,
        src: assetSrc("Heart"),
      },
      {
        type: "image",
        name: "Blossom",
        x: 850,
        y: 1120,
        width: 90,
        height: 90,
        src: assetSrc("Blossom"),
      },
      {
        type: "image",
        name: "Notebook paper",
        x: 140,
        y: 1520,
        width: 800,
        height: 260,
        src: assetSrc("Lined paper"),
      },
      {
        type: "text",
        name: "Caption",
        x: 190,
        y: 1590,
        width: 700,
        height: 140,
        text: {
          content: "First smiles, first steps, first everything.",
          fontSize: 30,
          fontWeight: 500,
        },
      },
    ],
  },
  {
    id: "wedding-day",
    name: "Wedding Day",
    description: "A romantic classic-ratio page for your wedding photos.",
    category: "Romance",
    frame: { width: 1600, height: 1200 },
    swatch: "from-rose-300/40 to-pink-200/30",
    objects: [
      {
        type: "text",
        name: "Title",
        x: 150,
        y: 70,
        width: 1300,
        height: 120,
        text: {
          content: "Forever Starts Today",
          fontSize: 60,
          fontWeight: 700,
          color: "#9d174d",
        },
      },
      {
        type: "text",
        name: "Subtitle",
        x: 300,
        y: 195,
        width: 1000,
        height: 50,
        text: {
          content: "Two hearts, one beautiful beginning",
          fontSize: 26,
          fontWeight: 500,
        },
      },
      {
        type: "image",
        name: "Photo frame",
        x: 600,
        y: 300,
        width: 400,
        height: 460,
        src: assetSrc("Gold frame"),
      },
      {
        type: "image",
        name: "Flower",
        x: 50,
        y: 30,
        width: 150,
        height: 150,
        src: assetSrc("Flower"),
      },
      {
        type: "image",
        name: "Flower",
        x: 1400,
        y: 30,
        width: 150,
        height: 150,
        src: assetSrc("Flower"),
      },
      {
        type: "image",
        name: "Heart",
        x: 980,
        y: 780,
        width: 90,
        height: 90,
        rotation: 10,
        src: assetSrc("Heart"),
      },
      {
        type: "image",
        name: "Washi tape",
        x: 560,
        y: 260,
        width: 220,
        height: 60,
        rotation: -8,
        src: assetSrc("Pink stripes"),
      },
      {
        type: "image",
        name: "Blush paper",
        x: 430,
        y: 800,
        width: 740,
        height: 140,
        src: assetSrc("Blush paper"),
      },
      {
        type: "text",
        name: "Caption",
        x: 480,
        y: 840,
        width: 640,
        height: 70,
        text: {
          content: "Happily Ever After",
          fontSize: 30,
          fontWeight: 500,
          color: "#9d174d",
        },
      },
    ],
  },
  {
    id: "blank-notes",
    name: "Notes & Memories",
    description: "A simple, minimal starter page for journaling.",
    category: "Minimal",
    frame: { width: 1600, height: 1200 },
    swatch: "from-emerald-300/40 to-teal-300/30",
    objects: [
      {
        type: "image",
        name: "Paper",
        x: 0,
        y: 0,
        width: 1600,
        height: 1200,
        src: assetSrc("Lined paper"),
      },
      {
        type: "text",
        name: "Title",
        x: 350,
        y: 440,
        width: 900,
        height: 100,
        text: { content: "Notes & Memories", fontSize: 52, fontWeight: 800 },
      },
      {
        type: "image",
        name: "Heart",
        x: 60,
        y: 60,
        width: 100,
        height: 100,
        rotation: -10,
        src: assetSrc("Heart"),
      },
      {
        type: "image",
        name: "Star",
        x: 1440,
        y: 1040,
        width: 100,
        height: 100,
        rotation: 15,
        src: assetSrc("Star"),
      },
    ],
  },
];
